[build-system]
requires = ["setuptools>=42.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--cov=sgn"
testpaths = ["tests"]

[tool.black]
line-length = 88
target-version = ['py37']
